version: '3.8'

services:
  db:
    container_name: postgres_db
    image: postgres:latest
    ports:
      - "5332:5432"
    environment:
      POSTGRES_USER: jefferscode
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - db:/data/postgres
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
